spring:
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/americano
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

logging:
  level:
    jdbc.audit: off
    jdbc.resultset: off
    jdbc.sqlonly: off